Fix/perform interaction close pop up
LuxoftSDL/sdl_core pull request #256
Opened 2021-12-20 15:36 UTC by VadymLuchko

Fixes #[FORDTCN-12832]

This PR is **[ready ]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
ATF and manual

### Summary
In the PR we prevent to sending redundant UI.ClosePopUp request for VR interaction mode

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-12-20 15:47 UTC, RomanReznichenkoLuxoft approved these changes

2021-12-20 17:29 UTC, OlhaVorobiova approved these changes

2021-12-20 19:02 UTC, ychernysheva requested changes

2021-12-20 19:02 UTC, ychernysheva commented on src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc
> +  const bool isSucess = hmi_apis::Common_Result::REJECTED != code;
```suggestion
  const bool isResultSuccessful = hmi_apis::Common_Result::REJECTED != code;
```

2021-12-29 10:20 UTC, ychernysheva requested changes

2021-12-29 10:20 UTC, ychernysheva commented on src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/perform_interaction_request.cc
>        InteractionMode::MANUAL_ONLY != interaction_mode_ && isSucess) {
please fix variable isSucess here and in other places

2022-01-20 14:34 UTC, LitvinenkoIra commented
moved to open

2022-01-20 14:34 UTC, closed without merging